# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3-stretch-node-browsers
      - image: circleci/node:9.9

    branches:
        only:
          - dev

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:YlIJx6uH3OUb3hxN+PAiJKlC+EGZ2KYi8VHxsfdJpLk=
      - DB_CONNECTION: sqlite
      - APP_URL: http://localhost

    steps:
      - checkout

      # Install PHP Extension
      # - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo apt-get update && sudo apt-get -y install mecab libmecab-dev mecab-ipadic-utf8 && git clone https://github.com/rsky/php-mecab.git && cd php-mecab/mecab/ && phpize && ./configure && make && sudo make install && sudo php -r "\$h=fopen('/etc/php.ini','a');fwrite(\$h,'extension=mecab.so'.\"\n\");";

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: yarn install

      # run tests!
      ## PHP Test
      - run: composer test
      ## JS Test
      - run: npm run test
      # push master
      - run: git config user.email "wevorence@gmail.com"
      - run: git config user.name "circleci"
      - run: git checkout master
      - run: git merge dev
      - run: git push origin master
